server:
  port: 8080

spring:
  application:
    name: spring-member-gateway

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus

logging:
  charset:
    console: UTF-8
  level:
    com.springmsa.membergateway: debug
    org.springframework.cloud.gateway: debug
